@vote_counter_HostAddress = http://localhost:5241

### Cast a vote
POST {{vote_counter_HostAddress}}/api/VoteCasting
Content-Type: application/json

{
  "candidate1": 1,
  "candidate2": 2,
  "candidate3": 3,
  "candidate4": 4,
  "electionId": 123,
  "timestamp": "2025-03-04T12:00:00Z"
}



###
